name: esteladevega_tfg_cubex
description: "Aplicación Flutter para resolver, analizar cubos de Rubik y hablar con la comunidad | 
              TFG DAM 24/25 | Estela de Vega Martín | IES Ribera de Castilla."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  vibration: ^3.1.3
  audioplayers: ^6.4.0
  timezone: ^0.10.0
  permission_handler: ^11.0.0
  flutter_local_notifications: ^19.1.0
  syncfusion_flutter_charts: ^29.1.35
  share_plus: ^7.0.0
  pdf: ^3.11.3
  printing: ^5.14.2
  dropdown_button2: ^2.3.9
  flutter_smart_dialog: ^4.9.8+7
  flutter_speed_dial: ^5.1.0
  popup_menu: ^2.1.0
  custom_pop_up_menu: any
  popover: ^0.3.1
  curved_navigation_bar: ^1.0.1
  stroke_text: any
  sqflite: ^2.4.1
  sqflite_common_ffi: ^2.3.4+3
  path: ^1.8.0
  crypto: ^3.0.1
  logger: ^1.1.0
  provider: ^6.1.2
  flutter_markdown: ^0.6.17
  url_launcher: ^6.0.10
  image_picker: ^1.0.4
  shared_preferences: ^2.2.2
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter:
    sdk: flutter
  file_picker: ^8.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.0.0
  flutter_lints: ^4.0.0
  test: ^1.20.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: assets/app_logo.png

flutter:
  generate: true
  assets:
    - assets/database/databaseCubeX.db
    - assets/background_intro.jpeg
    - assets/app_logo.png
    - assets/default_user_image.png
    - assets/session_icon.png
    - assets/trash-list.png
    - assets/cubix/
    - assets/sound_alerts/
  fonts:
    - family: JollyLodger
      fonts:
        - asset: assets/fonts/JollyLodger-Regular.ttf
    - family: Gluten
      fonts:
        - asset: assets/fonts/Gluten-Bold.otf
    - family: Broadway
      fonts:
        - asset: assets/fonts/BroadwayFlat.ttf
  uses-material-design: true
