name: esteladevega_tfg_cubex
description: "Aplicación Flutter para resolver, analizar cubos de Rubik y hablar con la comunidad | 
              TFG DAM 24/25 | Estela de Vega Martín | IES Ribera de Castilla."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
