name: esteladevega_tfg_cubex
description: "Aplicación Flutter para resolver, analizar cubos de Rubik y hablar con la comunidad | 
              TFG DAM 24/25 | Estela de Vega Martín | IES Ribera de Castilla."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  sqflite: ^2.4.1
  sqflite_common_ffi: ^2.3.4+3
  path: ^1.8.0
  crypto: ^3.0.1
  logger: ^1.1.0
  provider: ^6.1.2
  flutter_markdown: ^0.6.17
  url_launcher: ^6.0.10
  image_picker: ^1.0.4
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter:
    sdk: flutter
  file_picker: ^8.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  generate: true
  assets:
    - assets/background_intro.jpeg
    - assets/app_logo.png
    - assets/default_user_image.png
    - assets/session_icon.png
  fonts:
    - family: JollyLodger
      fonts:
        - asset: assets/fonts/JollyLodger-Regular.ttf
    - family: Gluten
      fonts:
        - asset: assets/fonts/Gluten-Bold.otf
  uses-material-design: true
